name: bdcc-final-exam
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.9
  - pyspark==3.5.4
  - pandas==2.2.3
  - matplotlib==3.10.3
  - numpy==1.26.4
  - pip
  - pip:
      - python-dotenv==1.1.0
      - apache-sedona==1.7.1
      - geopandas==1.0.1
      - tqdm==4.67.1